apiVersion: apps/v1
kind: Deployment
metadata:
  name: yashrepo
  namespace: default
  labels:
    app: yashrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yashrepo
  template:
    metadata:
      labels:
        app: yashrepo
    spec:
      containers:
      - name: yashrepo
        image:  public.ecr.aws/k7y1q1q5/yashrepo@sha256:9946908a9d188b8d8fdcb386f4c9327e8739bd92538cdc986e1e4db168b9df00
---
apiVersion: v1
kind: Service
metadata:
  name: yashrepo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: yashrepo
  ports:
  - port: 80
    targetPort: 80
