apiVersion: apps/v1
kind: Deployment
metadata:
  name: yashrepo
  namespace: default
  labels:
    app: yashrepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yashrepo
  template:
    metadata:
      labels:
        app: yashrepo
    spec:
      containers:
      - name: yashrepo
        image:  public.ecr.aws/k7y1q1q5/yashrepo:latest
---
apiVersion: v1
kind: Service
metadata:
  name: yashrepo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: yashrepo
  ports:
  - port: 80
    targetPort: 80
