name: Deploy to EKS

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Build and push Docker image to ECR
        run: |
         aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k7y1q1q5
          docker build -t yashrepo .
          docker tag yashrepo:latest public.ecr.aws/k7y1q1q5/yashrepo:latest
          docker push public.ecr.aws/k7y1q1q5/yashrepo:latest

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name aditya


      - name: Deploy to EKS
        run: kubectl apply -f resources.yaml
